### ISSUE TITLE
Melhorar a experiência com o FullScreen e com o Zoom

### ISSUE THREAD

**Issue by Pedro-Varela** [geoia/website#33]
Durante a sessão de pair programming, foi identificado alguns erros relacionados a zoom e ao botão de fullscreen. O botão de fullscreen apenas funciona para entrar em modo fullscreen e não funciona para sair. O zoom se comporta de maneira estranha ao centralizar no polígono selecionado sempre que o botão de queimadas é habilitado.
- [x] Botão Fullscreen
- [x] Queimadas alterando o zoom

**Comment by Pedro-Varela** [comment]
Encontrei uma maneira de resolver o problema de zoom ao ativar o botão de showFire mas não tenho certeza se é a maneira correta ou segura de se consertar.
Aguardo ajuda do professor.

**Comment by hsborges** [comment]
A refatoração feita e enviada no commit eac76b3082a20185c5fcac46b2e894efa216a246 resolveu o problema de mudança constante no zoom
