### ISSUE TITLE
Criar opção para mostrar/esconder limites municipais

### ISSUE THREAD

**Issue by Pedro-Varela** [geoia/website#37]

**Comment by Pedro-Varela** [comment]
@hsborges, @Pedrao1234  gostaria de ver com vocês algumas alternativas de ícones para essa feature.

O projeto utiliza apenas ícones que são oferecidos pelo MUI, então eu procurei ícones apenas por lá, e achei poucas opções que de fato remetessem ao que essa feature realiza, algumas alternativas propostas por mim são essas:

![Image](https://github.com/geoia/website/assets/64024622/af1e29d6-4ab2-4db0-952f-6bce7ae64d11)


![Image](https://github.com/geoia/website/assets/64024622/ad6b115b-b6c4-443e-a9db-33511817a1f9)

Ou essas


![Image](https://github.com/geoia/website/assets/64024622/b97183b2-c7d8-4d07-84f6-13800039c414)


![Image](https://github.com/geoia/website/assets/64024622/ab506af6-1e02-47d5-82e7-6108aaf49b13)

Creio que, se quisermos algo que remetesse melhor essa feature, talvez seja necessário a busca de ícones por outro lugar e não só pelo MUI.
Pelas minhas pesquisas no MUI, não achei nada melhor que esses 2.

**Comment by Pedrao1234** [comment]
Gostei dessa segunda sugestão de ícone, mas concordo que talvez seja interessante buscar por ícones além do MUI.

**Comment by Pedro-Varela** [comment]
No PR #38 foi adicionado as mudanças feitas nessa issue juntamente com as mudanças da issue #32
